# Name of your application. Used to uniquely configure containers.
service: qero

# Name of the container image.
image: paganotoni/qero

# Deploy to these servers.
servers:
  web:
    - <%= ENV['PRODUCTION_SERVER_IP'] %>

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: qero.antoniopagano.com

# Credentials for your image host.
registry:
  server: localhost:5555

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    SESSION_NAME: "qero_session"
    GO_ENV: "production"
  secret:
    - SESSION_SECRET
